
import React from 'react';

type ModalType = 'terms' | 'privacy' | null;

interface LegalModalProps {
  isOpen: boolean;
  type: ModalType;
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, type, onClose }) => {
  if (!isOpen || !type) return null;

  const content = {
    terms: {
      title: 'Terms of Service',
      body: (
        <div className="space-y-4 text-gray-600 text-sm leading-relaxed">
          <p><strong>1. Introduction</strong><br/>Welcome to QR Code Generator. By accessing and using this application, you accept and agree to be bound by the terms and provision of this agreement.</p>
          <p><strong>2. Use License</strong><br/>This application is a free tool provided for both personal and commercial use. You are free to use the QR codes generated by this application without attribution, although it is appreciated.</p>
          <p><strong>3. Disclaimer</strong><br/>The materials on this application are provided "as is". We make no warranties, expressed or implied, and hereby disclaim and negate all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
          <p><strong>4. Limitations</strong><br/>In no event shall the creators of this application be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on this site.</p>
        </div>
      )
    },
    privacy: {
      title: 'Privacy Policy',
      body: (
        <div className="space-y-4 text-gray-600 text-sm leading-relaxed">
          <p><strong>1. Data Collection</strong><br/>We prioritize your privacy. This application operates entirely <strong>client-side</strong> within your web browser. We do not collect, store, or transmit your input data (URLs, text, Wi-Fi credentials, or contact information) to any server.</p>
          <p><strong>2. QR Code Generation</strong><br/>The QR code images are generated locally on your device. No image data is uploaded to the cloud.</p>
          <p><strong>3. Cookies & Tracking</strong><br/>We do not use cookies to track your personal browsing behavior. Any local storage used is strictly for maintaining your user interface preferences (if applicable).</p>
          <p><strong>4. Third-Party Links</strong><br/>Our application may contain links to external sites (e.g., in the generated QR code content). If you click on a third-party link, you will be directed to that site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        </div>
      )
    }
  };

  const currentContent = content[type];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <style>{`
        @keyframes modalFadeIn {
          from { opacity: 0; transform: scale(0.95); }
          to { opacity: 1; transform: scale(1); }
        }
      `}</style>
      
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/30 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      />
      
      {/* Modal Content */}
      <div 
        className="relative bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col max-h-[90vh]"
        style={{ animation: 'modalFadeIn 0.2s ease-out' }}
      >
        <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/50 shrink-0">
          <h3 className="text-lg font-semibold text-gray-900">{currentContent.title}</h3>
          <button 
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors p-1 rounded-full hover:bg-gray-100"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
            </svg>
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto custom-scrollbar">
          {currentContent.body}
        </div>
        
        <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 flex justify-end shrink-0">
          <button 
            onClick={onClose}
            className="px-4 py-2 bg-white border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
